"use client";

import { useState } from "react";
import { useAuth } from "@clerk/nextjs";
import { ArrowLeft, CheckCircle2, Code2, Copy, Database, Fingerprint, GitBranch, Lock, Play, RotateCcw, ShieldCheck, Sparkles } from "lucide-react";

import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { addMemories, displayApiError, getMemoryJob, retrieveMemories, type MemoryJobStatus, type MemoryRecord } from "@/lib/api";

type Screen = "engine" | "init" | "mode" | "single-input" | "single-load" | "single-result" | "conflict-one" | "conflict-two" | "conflict-review" | "conflict-load" | "conflict-result" | "passport-agent" | "passport-load" | "passport-memory" | "passport-consent" | "passport-done";
type Agent = { name: string; authority: string; claim: string };
type RunResult = { userId: string; jobs: MemoryJobStatus[]; memories: MemoryRecord[]; prompt: string; summary: string; error?: string };
type Tab = { id: string; label: string; icon?: React.ReactNode; content: React.ReactNode };

const VIOLET = "#7C3AED";
const singleDefault = "I prefer concise technical answers, Python examples, and step-by-step debugging when the issue is difficult.";
const billingDefault: Agent = { name: "Billing Agent", authority: "Source of truth for subscriptions", claim: "User is on Growth plan at Rs. 999/month." };
const supportDefault: Agent = { name: "Support Agent", authority: "Handles refunds and support tickets", claim: "User downgraded to Starter last week." };

function cx(...items: Array<string | false | null | undefined>) { return items.filter(Boolean).join(" "); }
function sleep(ms: number) { return new Promise((resolve) => window.setTimeout(resolve, ms)); }
function slug(value: string, fallback: string) { return value.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "") || fallback; }
function playgroundUser(prefix: string) { return `${prefix}_${typeof crypto !== "undefined" && "randomUUID" in crypto ? crypto.randomUUID().slice(0, 8) : String(Date.now()).slice(-8)}`; }
function done(job: MemoryJobStatus) { return ["completed", "complete", "processed", "success", "failed", "dead", "error"].includes(job.status.toLowerCase()); }
function failed(job: MemoryJobStatus) { return ["failed", "dead", "error"].includes(job.status.toLowerCase()) || Boolean(job.error || job.error_summary); }
function stored(job: MemoryJobStatus) { return job.memories_created ?? job.memories_extracted ?? 0; }

function Shell({ children, onBack }: { children: React.ReactNode; onBack?: () => void }) {
  return (
    <main className="relative -m-6 min-h-[calc(100vh-2rem)] overflow-hidden bg-black px-5 py-8 text-white md:-m-8 md:px-10">
      <div className="pointer-events-none absolute inset-0 opacity-50 [background:radial-gradient(circle_at_20%_15%,rgba(124,58,237,0.28),transparent_34%),radial-gradient(circle_at_85%_20%,rgba(14,165,233,0.14),transparent_30%),linear-gradient(180deg,#000,#050505)]" />
      <div className="pointer-events-none absolute inset-0 bg-[linear-gradient(rgba(255,255,255,0.035)_1px,transparent_1px),linear-gradient(90deg,rgba(255,255,255,0.035)_1px,transparent_1px)] bg-[size:72px_72px] opacity-20" />
      {onBack ? <button onClick={onBack} className="absolute left-6 top-6 z-20 inline-flex items-center gap-2 rounded-full border border-white/10 bg-white/5 px-4 py-2 text-sm font-bold text-white backdrop-blur hover:border-violet-400"><ArrowLeft className="size-4" /> Back</button> : null}
      <div className="relative z-10 mx-auto flex min-h-[calc(100vh-5rem)] w-full max-w-6xl flex-col items-center justify-center">{children}</div>
    </main>
  );
}

function Title({ eyebrow, title, subtitle }: { eyebrow?: string; title: string; subtitle?: string }) {
  return <div className="mx-auto mb-8 max-w-4xl text-center">{eyebrow ? <p className="mb-4 text-sm font-black uppercase tracking-[0.32em] text-violet-300">{eyebrow}</p> : null}<h1 className="text-4xl font-black leading-tight md:text-6xl">{title}</h1>{subtitle ? <p className="mx-auto mt-5 max-w-3xl text-xl leading-8 text-zinc-300 md:text-2xl">{subtitle}</p> : null}</div>;
}

function Primary({ children, onClick, disabled, ghost }: { children: React.ReactNode; onClick: () => void; disabled?: boolean; ghost?: boolean }) {
  return <Button onClick={onClick} disabled={disabled} className={cx("h-14 rounded-2xl px-7 text-base font-black text-white transition hover:-translate-y-0.5 disabled:opacity-40", ghost ? "border border-white/10 bg-white/5 shadow-none hover:bg-white/10" : "border-0 shadow-[0_16px_50px_rgba(124,58,237,0.35)]")} style={ghost ? undefined : { backgroundColor: VIOLET }}>{children}</Button>;
}

function Option({ title, subtitle, icon, onClick }: { title: string; subtitle: string; icon: React.ReactNode; onClick: () => void }) {
  return <button onClick={onClick} className="group w-full rounded-[2rem] border border-white/10 bg-white/[0.04] p-7 text-left shadow-2xl shadow-black/40 backdrop-blur transition hover:-translate-y-1 hover:border-violet-400 hover:bg-violet-500/10"><div className="mb-5 inline-flex size-12 items-center justify-center rounded-2xl bg-violet-500/15 text-violet-200 ring-1 ring-violet-400/30 group-hover:bg-violet-600">{icon}</div><h2 className="text-3xl font-black md:text-4xl">{title}</h2><p className="mt-3 text-xl leading-8 text-zinc-300">{subtitle}</p></button>;
}

function Spinner({ label, subtitle }: { label: string; subtitle?: string }) {
  return <div className="flex min-h-[520px] flex-col items-center justify-center text-center"><div className="relative size-40 animate-spin rounded-full [animation-duration:1.1s]">{Array.from({ length: 12 }).map((_, i) => <span key={i} className="absolute left-1/2 top-1/2 h-9 w-3 origin-[50%_72px] rounded-full shadow-[0_0_18px_rgba(124,58,237,0.8)]" style={{ backgroundColor: VIOLET, opacity: 0.2 + i * 0.06, transform: `translate(-50%, -72px) rotate(${i * 30}deg)` }} />)}</div><h1 className="mt-10 text-4xl font-black md:text-6xl">{label}</h1><p className="mt-5 max-w-2xl text-xl leading-8 text-zinc-300 md:text-2xl">{subtitle ?? "MemoryOS is preparing extraction, scoring, source checks, and retrieval context."}</p></div>;
}

function Progress({ active }: { active: number }) {
  return <div className="grid w-full max-w-3xl grid-cols-2 gap-3 md:grid-cols-4">{["Events", "Extract", "Resolve", "Retrieve"].map((item, i) => <div key={item} className="rounded-3xl border border-white/10 bg-white/[0.04] p-4"><div className="flex items-center gap-2 text-sm font-black uppercase tracking-[0.18em] text-zinc-300"><span className={cx("size-3 rounded-full", i <= active ? "bg-violet-400" : "bg-zinc-700")} />{item}</div><div className="mt-4 h-2 overflow-hidden rounded-full bg-zinc-800"><div className="h-full rounded-full bg-violet-500 transition-all" style={{ width: i <= active ? "100%" : "25%" }} /></div></div>)}</div>;
}

function Tabs({ tabs }: { tabs: Tab[] }) {
  const [active, setActive] = useState(tabs[0]?.id ?? "");
  const tab = tabs.find((item) => item.id === active) ?? tabs[0];
  return <section className="w-full rounded-[2rem] border border-white/10 bg-white/[0.04] p-4 shadow-2xl shadow-black/30 backdrop-blur"><div className="mb-4 flex flex-wrap gap-3">{tabs.map((item) => <button key={item.id} onClick={() => setActive(item.id)} className={cx("inline-flex items-center gap-2 rounded-full border px-4 py-2 text-sm font-black transition", active === item.id ? "border-violet-400 bg-violet-600 text-white" : "border-white/10 bg-black/40 text-zinc-300 hover:border-violet-400")}>{item.icon}{item.label}</button>)}</div><div className="min-h-[320px] rounded-[1.5rem] border border-white/10 bg-black/70 p-6 text-lg leading-8 text-zinc-200">{tab?.content}</div></section>;
}

function Code({ code }: { code: string }) { return <pre className="max-h-[440px] overflow-auto rounded-2xl bg-zinc-950 p-5 text-sm leading-7 text-violet-100">{code}</pre>; }
function ResultSummary({ result }: { result: RunResult | null }) { return !result ? <p>Waiting for result...</p> : <div className="space-y-5"><div className="rounded-2xl border border-emerald-400/20 bg-emerald-400/10 p-5"><p className="text-2xl font-black text-white">{result.summary}</p></div><p className="text-zinc-300">External user ID: <span className="font-mono text-violet-200">{result.userId}</span></p>{result.error ? <p className="rounded-2xl border border-red-400/30 bg-red-950/50 p-5 text-red-200">{result.error}</p> : null}</div>; }
function MemoryList({ records }: { records: MemoryRecord[] }) { return !records.length ? <p>No retrievable memories returned yet. If a weak signal was buffered, repeat the fact once to reinforce it.</p> : <div className="space-y-4">{records.map((m) => <div key={m.id} className="rounded-2xl border border-white/10 bg-white/[0.04] p-5"><div className="flex flex-wrap items-start justify-between gap-3"><p className="max-w-3xl text-xl font-semibold text-white">{m.content}</p><span className="rounded-full bg-violet-600 px-3 py-1 text-sm font-black text-white">{Number(m.importance_score ?? 0).toFixed(1)}</span></div><div className="mt-4 flex flex-wrap gap-2 text-xs font-bold uppercase tracking-[0.14em] text-zinc-300"><span className="rounded-full bg-white/10 px-3 py-1">{m.category}</span>{m.provenance?.service ? <span className="rounded-full bg-violet-500/20 px-3 py-1 text-violet-200">via {m.provenance.service}</span> : null}</div></div>)}</div>; }
function JobList({ jobs }: { jobs: MemoryJobStatus[] }) { return !jobs.length ? <p>No extraction job was created. The quality gate may have skipped or blocked this turn.</p> : <div className="space-y-4">{jobs.map((job) => <div key={job.job_id} className="rounded-2xl border border-white/10 bg-white/[0.04] p-5"><div className="flex flex-wrap items-center justify-between gap-3"><p className="font-mono text-sm text-zinc-300">{job.job_id}</p><span className="rounded-full border border-violet-400 px-3 py-1 text-sm font-black text-violet-200">{job.status}</span></div><p className="mt-3 text-zinc-300">stored {stored(job)} | buffered {job.pending_candidates_buffered ?? 0} | promoted {job.pending_candidates_promoted ?? 0} | attempts {job.attempts ?? 0}</p>{job.extraction_metadata ? <Code code={JSON.stringify(job.extraction_metadata, null, 2)} /> : null}{job.error || job.error_summary ? <p className="mt-3 text-red-300">{job.error_summary ?? job.error}</p> : null}</div>)}</div>; }

function AgentForm({ agent, onChange, onNext, extra }: { agent: Agent; onChange: (agent: Agent) => void; onNext: () => void; extra?: React.ReactNode }) {
  return <div className="w-full max-w-4xl space-y-4 rounded-[2rem] border border-white/10 bg-white/[0.04] p-5 backdrop-blur"><Input value={agent.name} onChange={(e) => onChange({ ...agent, name: e.target.value })} placeholder="Agent name" className="h-14 border-white/10 bg-black/50 px-4 text-lg text-white placeholder:text-zinc-500" /><Input value={agent.authority} onChange={(e) => onChange({ ...agent, authority: e.target.value })} placeholder="Authority, for example: Source of truth for subscriptions" className="h-14 border-white/10 bg-black/50 px-4 text-lg text-white placeholder:text-zinc-500" /><textarea value={agent.claim} onChange={(e) => onChange({ ...agent, claim: e.target.value })} placeholder="What does this agent say?" className="min-h-36 w-full rounded-2xl border border-white/10 bg-black/50 p-4 text-lg leading-8 text-white outline-none ring-violet-500/20 transition placeholder:text-zinc-500 focus:ring-4" /><div className="flex flex-wrap gap-3"><Primary onClick={onNext} disabled={!agent.name.trim() || !agent.authority.trim() || !agent.claim.trim()}>Next</Primary>{extra}</div></div>;
}
function ConflictPreview({ agent }: { agent: Agent }) { return <div className="rounded-[2rem] border border-white/10 bg-white/[0.04] p-6"><p className="text-sm font-black uppercase tracking-[0.22em] text-violet-300">{agent.authority}</p><h3 className="mt-3 text-3xl font-black text-white">{agent.name}</h3><p className="mt-5 text-xl leading-8 text-zinc-200">{agent.claim}</p></div>; }
function Completion({ show, restart, share, label }: { show: boolean; restart: () => void; share: () => void; label: string }) { return !show ? null : <div className="fixed bottom-5 left-1/2 z-30 flex w-[calc(100%-2rem)] max-w-3xl -translate-x-1/2 flex-wrap items-center justify-between gap-3 rounded-3xl border border-white/10 bg-black/90 p-3 shadow-2xl shadow-black backdrop-blur"><span className="px-3 text-base font-black text-white">MemoryOS Playground complete.</span><div className="flex gap-2"><Primary ghost onClick={restart}><RotateCcw className="mr-2 size-4" />Restart</Primary><Primary onClick={share}><Copy className="mr-2 size-4" />{label}</Primary></div></div>; }
function PassportMemory() { return <div className="grid w-full max-w-5xl gap-4 md:grid-cols-2">{[["Goals", "Ship a reliable AI product without losing context between sessions."], ["Preferences", "Prefers direct technical explanations with code when useful."], ["Facts", "Works mostly with Python, TypeScript, and backend systems."], ["Control", "Can revoke agent access or remove individual memories anytime."]].map(([title, value]) => <div key={title} className="rounded-[2rem] border border-white/10 bg-white/[0.04] p-6"><p className="text-sm font-black uppercase tracking-[0.22em] text-violet-300">{title}</p><p className="mt-4 text-xl leading-8 text-white">{value}</p></div>)}</div>; }

export default function PlaygroundPage() {
  const { getToken } = useAuth();
  const [screen, setScreen] = useState<Screen>("engine");
  const [previous, setPrevious] = useState<Screen>("engine");
  const [engine, setEngine] = useState<"general" | "domain" | null>(null);
  const [single, setSingle] = useState(singleDefault);
  const [agentOne, setAgentOne] = useState<Agent>(billingDefault);
  const [agentTwo, setAgentTwo] = useState<Agent>(supportDefault);
  const [passportAgent, setPassportAgent] = useState("Python Coding Assistant");
  const [singleResult, setSingleResult] = useState<RunResult | null>(null);
  const [conflictResult, setConflictResult] = useState<RunResult | null>(null);
  const [copyLabel, setCopyLabel] = useState("Share");

  async function poll(jobId: string) { let latest: MemoryJobStatus | null = null; for (let i = 0; i < 15; i += 1) { latest = await getMemoryJob(getToken, jobId); if (done(latest)) return latest; await sleep(1500); } return latest ?? { job_id: jobId, status: "processing" }; }
  async function initialize(kind: "general" | "domain") { setEngine(kind); setPrevious("engine"); setScreen("init"); await sleep(1500); setScreen("mode"); }
  function choose(mode: "single" | "conflict" | "passport") { setScreen(mode === "single" ? "single-input" : mode === "conflict" ? "conflict-one" : "passport-agent"); }
  function back() { if (screen === "mode") setScreen("engine"); else if (["single-input", "conflict-one", "passport-agent"].includes(screen)) setScreen("mode"); else if (screen === "single-result") setScreen("single-input"); else if (screen === "conflict-two") setScreen("conflict-one"); else if (screen === "conflict-review") setScreen("conflict-two"); else if (screen === "conflict-result") setScreen("conflict-review"); else if (screen === "passport-memory") setScreen("passport-agent"); else if (screen === "passport-consent") setScreen("passport-memory"); else if (screen === "passport-done") setScreen("passport-memory"); else setScreen(previous); }
  function restart() { setScreen("engine"); setEngine(null); setSingle(singleDefault); setAgentOne(billingDefault); setAgentTwo(supportDefault); setPassportAgent("Python Coding Assistant"); setSingleResult(null); setConflictResult(null); }
  async function share() { await navigator.clipboard.writeText("MemoryOS Playground: live extraction, source-aware conflict handling, and Memory Passport control."); setCopyLabel("Copied"); window.setTimeout(() => setCopyLabel("Share"), 1400); }

  async function runSingle() {
    const userId = playgroundUser("playground_single"); setPrevious(screen); setSingleResult(null); setScreen("single-load");
    try { const add = await addMemories(getToken, { external_user_id: userId, messages: [{ role: "user", content: single }, { role: "assistant", content: "I will remember durable preferences for future sessions." }], metadata: { source: "tenant_playground", mode: "single" } }); const jobs = add.job_id ? [await poll(add.job_id)] : []; const retrieved = await retrieveMemories(getToken, { external_user_id: userId, query: single, limit: 8, format: "bullets", context_max_tokens: 700 }); const created = jobs.reduce((s, j) => s + stored(j), 0); const buffered = jobs.reduce((s, j) => s + (j.pending_candidates_buffered ?? 0), 0); const bad = jobs.find(failed); setSingleResult({ userId, jobs, memories: retrieved.data, prompt: retrieved.system_prompt_addition, summary: bad ? `Extraction finished with an error: ${bad.error_summary ?? bad.error ?? "unknown error"}.` : `${created} memory records stored${buffered ? ` and ${buffered} weak signal buffered` : ""}. Retrieval returned ${retrieved.data.length} records.` }); } catch (error) { setSingleResult({ userId, jobs: [], memories: [], prompt: "", summary: "Live backend call failed.", error: displayApiError(error) ?? "Unable to run the playground right now." }); } finally { setScreen("single-result"); }
  }

  async function runConflict() {
    const userId = playgroundUser("playground_conflict"); setPrevious(screen); setConflictResult(null); setScreen("conflict-load");
    try { const first = await addMemories(getToken, { external_user_id: userId, messages: [{ role: "user", content: `${agentTwo.name} says: ${agentTwo.claim}` }, { role: "assistant", content: `${agentTwo.name} reported: ${agentTwo.claim}` }], source: { service: slug(agentTwo.name, "support-agent"), event_id: `playground-${slug(agentTwo.name, "support")}-${userId}`, scope: { authority: agentTwo.authority, demo: "multi-service-conflict" } }, metadata: { source: "tenant_playground", authority: agentTwo.authority } }); const second = await addMemories(getToken, { external_user_id: userId, messages: [{ role: "user", content: `${agentOne.name} says: ${agentOne.claim}` }, { role: "assistant", content: `${agentOne.name} reported: ${agentOne.claim}` }], source: { service: slug(agentOne.name, "billing-agent"), event_id: `playground-${slug(agentOne.name, "billing")}-${userId}`, scope: { authority: agentOne.authority, demo: "multi-service-conflict" } }, metadata: { source: "tenant_playground", authority: agentOne.authority } }); const ids = [first.job_id, second.job_id].filter((id): id is string => Boolean(id)); const jobs: MemoryJobStatus[] = []; for (const id of ids) jobs.push(await poll(id)); const retrieved = await retrieveMemories(getToken, { external_user_id: userId, query: "What is the user's current subscription plan?", limit: 10, format: "bullets", context_max_tokens: 900 }); const created = jobs.reduce((s, j) => s + stored(j), 0); const buffered = jobs.reduce((s, j) => s + (j.pending_candidates_buffered ?? 0), 0); setConflictResult({ userId, jobs, memories: retrieved.data, prompt: retrieved.system_prompt_addition, summary: `${created} memory records stored${buffered ? ` and ${buffered} weak signal buffered` : ""}. MemoryOS returned ${retrieved.data.length} source-aware records.` }); } catch (error) { setConflictResult({ userId, jobs: [], memories: [], prompt: "", summary: "Live backend call failed.", error: displayApiError(error) ?? "Unable to run the conflict demo right now." }); } finally { setScreen("conflict-result"); }
  }

  async function loadPassport() { setPrevious(screen); setScreen("passport-load"); await sleep(1500); setScreen("passport-memory"); }
  async function consentPreview() { setScreen("passport-consent"); const base = process.env.NEXT_PUBLIC_CONSENT_BASE_URL; if (base) window.open(base, "_blank", "noopener,noreferrer"); await sleep(3000); setScreen("passport-done"); }

  const singleCode = `from memoryos import Memory\n\nmem = Memory(api_key="mem_live_xxx")\nmem.add(external_user_id="${singleResult?.userId ?? "user_123"}", messages=[{"role": "user", "content": "${single.replaceAll('"', '\\"')}"}])\ncontext = mem.get(external_user_id="${singleResult?.userId ?? "user_123"}", query="How should I answer this user?")`;
  const conflictCode = `from memoryos import Memory\n\nmem = Memory(api_key="mem_live_xxx")\nmem.add(external_user_id="${conflictResult?.userId ?? "customer_123"}", messages=[{"role": "assistant", "content": "${agentOne.claim.replaceAll('"', '\\"')}"}], source=Memory.source("${slug(agentOne.name, "billing-agent")}"))\nmem.add(external_user_id="${conflictResult?.userId ?? "customer_123"}", messages=[{"role": "assistant", "content": "${agentTwo.claim.replaceAll('"', '\\"')}"}], source=Memory.source("${slug(agentTwo.name, "support-agent")}"))`;
  const complete = screen === "single-result" || screen === "conflict-result" || screen === "passport-done";

  if (screen === "engine") return <Shell><Title title="What kind of memory engine do you want to explore?" subtitle="Start with one choice. The playground reveals details only when you ask for them." /><div className="grid w-full max-w-4xl gap-5 md:grid-cols-2"><Option title="General Engine" subtitle="Works across any agent or use case" icon={<Sparkles className="size-6" />} onClick={() => void initialize("general")} /><Option title="Domain-Specific Engine" subtitle="Optimized for EdTech, Customer Support, or Healthcare" icon={<Database className="size-6" />} onClick={() => void initialize("domain")} /></div></Shell>;
  if (screen === "init") return <Shell onBack={back}><Spinner label="Initializing MemoryOS engine..." /><Progress active={0} /></Shell>;
  if (screen === "mode") return <Shell onBack={back}><Title title="Choose your memory mode." subtitle={engine === "domain" ? "Domain engines use the same write, retrieval, provenance, and governance layer." : "Each flow is live or close to the real production flow."} /><div className="grid w-full max-w-4xl gap-5"><Option title="What does MemoryOS remember?" subtitle="Single-agent extraction, scoring, weak-signal buffering, and retrieval" icon={<Sparkles className="size-6" />} onClick={() => choose("single")} /><Option title="Multi-service agent conflict" subtitle="Two backend services write competing facts with source metadata" icon={<GitBranch className="size-6" />} onClick={() => choose("conflict")} /><Option title="User-approved cross-agent memory" subtitle="Memory Passport consent, scope, and revocation" icon={<Fingerprint className="size-6" />} onClick={() => choose("passport")} /></div></Shell>;
  if (screen === "single-input") return <Shell onBack={back}><Title title="What should your agent remember?" subtitle="Write one realistic user message. MemoryOS will decide whether to store, buffer, or skip it." /><div className="w-full max-w-4xl rounded-[2rem] border border-white/10 bg-white/[0.04] p-5"><textarea value={single} onChange={(e) => setSingle(e.target.value)} className="min-h-56 w-full rounded-2xl border border-white/10 bg-black/60 p-5 text-xl leading-8 text-white outline-none ring-violet-500/20 focus:ring-4" /><div className="mt-5 flex justify-end"><Primary onClick={() => void runSingle()} disabled={!single.trim()}><Play className="mr-2 size-5" />Store Memory</Primary></div></div></Shell>;
  if (screen === "single-load") return <Shell onBack={back}><Spinner label="Extracting and scoring..." subtitle="The backend is running the real memory write path." /><Progress active={1} /></Shell>;
  if (screen === "single-result") return <Shell onBack={back}><Title eyebrow="Outcome first" title="What MemoryOS did" /><Tabs tabs={[{ id: "summary", label: "Summary", icon: <ShieldCheck className="size-4" />, content: <ResultSummary result={singleResult} /> }, { id: "memories", label: "Extracted", icon: <Sparkles className="size-4" />, content: <MemoryList records={singleResult?.memories ?? []} /> }, { id: "jobs", label: "Job", icon: <Database className="size-4" />, content: <JobList jobs={singleResult?.jobs ?? []} /> }, { id: "prompt", label: "Prompt", icon: <Code2 className="size-4" />, content: <Code code={singleResult?.prompt || "No prompt context returned yet."} /> }, { id: "code", label: "Code", icon: <Code2 className="size-4" />, content: <Code code={singleCode} /> }]} /><Completion show={complete} restart={restart} share={share} label={copyLabel} /></Shell>;
  if (screen === "conflict-one") return <Shell onBack={back}><Title eyebrow="First service" title="Who owns the source of truth?" /><AgentForm agent={agentOne} onChange={setAgentOne} onNext={() => setScreen("conflict-two")} /></Shell>;
  if (screen === "conflict-two") return <Shell onBack={back}><Title eyebrow="Second service" title="Now add a competing claim." subtitle="Use a contradiction to feel the governance layer." /><AgentForm agent={agentTwo} onChange={setAgentTwo} onNext={() => setScreen("conflict-review")} extra={<Primary ghost onClick={() => { setAgentOne(billingDefault); setAgentTwo(supportDefault); }}>Use example conflict</Primary>} /></Shell>;
  if (screen === "conflict-review") return <Shell onBack={back}><Title title="Ready to run source-aware memory?" subtitle="MemoryOS will write both claims with source metadata, then retrieve the safest context." /><div className="grid w-full max-w-5xl gap-5 md:grid-cols-2"><ConflictPreview agent={agentOne} /><ConflictPreview agent={agentTwo} /></div><div className="mt-8"><Primary onClick={() => void runConflict()}><Play className="mr-2 size-5" />Run MemoryOS</Primary></div></Shell>;
  if (screen === "conflict-load") return <Shell onBack={back}><Spinner label="Resolving conflict..." subtitle="Writing both services, polling jobs, then retrieving source-aware context." /><Progress active={2} /></Shell>;
  if (screen === "conflict-result") { const sources = (conflictResult?.memories ?? []).map((m) => `${m.content}\nsource: ${m.provenance?.service ?? "unknown"}\nevent: ${m.provenance?.event_id ?? m.source_event_id ?? "unknown"}`).join("\n\n") || "No source records returned."; return <Shell onBack={back}><Title eyebrow="Outcome first" title="Conflict result" /><Tabs tabs={[{ id: "summary", label: "Summary", icon: <ShieldCheck className="size-4" />, content: <ResultSummary result={conflictResult} /> }, { id: "memories", label: "Extracted", icon: <Sparkles className="size-4" />, content: <MemoryList records={conflictResult?.memories ?? []} /> }, { id: "decision", label: "Decision", icon: <GitBranch className="size-4" />, content: <p>{conflictResult?.memories[0] ? `Top retrieved context: ${conflictResult.memories[0].content}` : "No winner was returned yet. Check the job tab for stored/buffered counts."}</p> }, { id: "sources", label: "Sources", icon: <Database className="size-4" />, content: <Code code={sources} /> }, { id: "jobs", label: "Jobs", icon: <Database className="size-4" />, content: <JobList jobs={conflictResult?.jobs ?? []} /> }, { id: "prompt", label: "Prompt", icon: <Code2 className="size-4" />, content: <Code code={conflictResult?.prompt || "No prompt context returned yet."} /> }, { id: "code", label: "Code", icon: <Code2 className="size-4" />, content: <Code code={conflictCode} /> }]} /><Completion show={complete} restart={restart} share={share} label={copyLabel} /></Shell>; }
  if (screen === "passport-agent") return <Shell onBack={back}><Title title="Name your Passport-enabled agent." subtitle="This previews the Memory Passport flow. Real grants are created from the Memory Passport dashboard." /><div className="w-full max-w-3xl rounded-[2rem] border border-white/10 bg-white/[0.04] p-5"><Input value={passportAgent} onChange={(e) => setPassportAgent(e.target.value)} className="h-14 border-white/10 bg-black/60 px-4 text-lg text-white" /><div className="mt-5 flex justify-end"><Primary onClick={() => void loadPassport()} disabled={!passportAgent.trim()}>Load Memories</Primary></div></div></Shell>;
  if (screen === "passport-load") return <Shell onBack={back}><Spinner label="Retrieving agent memory..." subtitle="Loading the user-controlled Memory Passport preview." /><Progress active={3} /></Shell>;
  if (screen === "passport-memory") return <Shell onBack={back}><Title eyebrow="Memory Passport" title={`${passportAgent} can request approved memory.`} subtitle="Agent IDs and private keys are not shown here. Create real agent identities from the Memory Passport dashboard." /><div className="mb-5 w-full max-w-5xl rounded-[2rem] border border-sky-400/30 bg-sky-950/40 p-5 text-sky-50"><p className="font-black">For the real Passport experience:</p><p className="mt-2">Create a Passport agent, generate a consent URL or secure-link connector, then let the user choose categories and revoke later.</p></div><PassportMemory /><div className="mt-8"><Primary onClick={() => void consentPreview()}><Lock className="mr-2 size-5" />Give Consent</Primary></div></Shell>;
  if (screen === "passport-consent") return <Shell onBack={back}><Title title="Consent portal opened." subtitle="In production, this is where the user reviews categories and grants access." /><Spinner label="Waiting for consent..." subtitle="The playground is simulating the return from the permission center." /></Shell>;
  return <Shell onBack={back}><Title eyebrow="Consent complete" title="Cross-agent access: limited" subtitle="The user approved preferences, goals, and facts. Other categories stay restricted." /><Tabs tabs={[{ id: "approved", label: "Approved", icon: <CheckCircle2 className="size-4" />, content: <div className="space-y-3"><p>Preferences: granted</p><p>Goals: granted</p><p>Facts: granted</p></div> }, { id: "restricted", label: "Restricted", icon: <Lock className="size-4" />, content: <div className="space-y-3"><p>Relationships: restricted</p><p>Expertise: restricted</p><p>The user can change this later.</p></div> }, { id: "code", label: "Integration", icon: <Code2 className="size-4" />, content: <Code code={`const consentUrl = UniversalMemoryOS.consentUrl(\n  "your_global_agent_id",\n  null,\n  "user_session_id",\n  ["preference", "goal", "fact"],\n);`} /> }]} /><Completion show restart={restart} share={share} label={copyLabel} /></Shell>;
}
